"use client";
import type { Metadata } from "next";
import LegalLayout, { Section, InfoBox } from "@/components/legal/LegalLayout";
import { useLang } from "@/context/LanguageContext";

const TOC_EN = [
  { id: "nature",      label: "Nature of Service" },
  { id: "ai",          label: "AI-Generated Content" },
  { id: "not-advice",  label: "Not Religious Advice" },
  { id: "context",     label: "Spiritual Context" },
  { id: "third-party", label: "Third-Party AI Services" },
  { id: "warranty",    label: "No Warranty" },
  { id: "user",        label: "User Responsibility" },
];

const TOC_HI = [
  { id: "nature",      label: "सेवा की प्रकृति" },
  { id: "ai",          label: "AI-जनित सामग्री" },
  { id: "not-advice",  label: "धार्मिक सलाह नहीं" },
  { id: "context",     label: "आध्यात्मिक संदर्भ" },
  { id: "third-party", label: "तृतीय-पक्ष AI सेवाएं" },
  { id: "warranty",    label: "कोई वारंटी नहीं" },
  { id: "user",        label: "उपयोगकर्ता की जिम्मेदारी" },
];

function ContentEN() {
  return (
    <>


      <Section id="nature">
        <h2>Nature of Service</h2>
        <InfoBox>
          <strong>Paramvani is an AI-powered entertainment and spiritual exploration platform.</strong> It is NOT a religious authority, spiritual guide, counsellor, or substitute for professional or religious advice of any kind.
        </InfoBox>
        <p>Paramvani creates simulated conversational experiences inspired by Hindu deities and spiritual concepts. These experiences are designed for personal reflection, cultural connection, and entertainment. They are powered by large language model (LLM) AI technology.</p>
      </Section>

      <Section id="ai">
        <h2>AI-Generated Content Disclosure</h2>
        <p>All responses generated by Paramvani&apos;s divine personas (including Lord Vishnu, Lord Hanuman, and others) are:</p>
        <ul>
          <li><strong>Artificially generated</strong> by a large language model (LLM), not by any human or spiritual authority.</li>
          <li><strong>Not authoritative</strong> — they do not represent the views, teachings, or words of any real deity, religious organisation, or spiritual institution.</li>
          <li><strong>Potentially inaccurate</strong> — AI can make errors, produce hallucinations, or present information out of context.</li>
          <li><strong>Contextually limited</strong> — the AI may not accurately reflect all scriptural or theological nuances.</li>
        </ul>
        <p>The AI personas are creative interpretations built for reflective, positive engagement. They are not channelling, prophecy, or any form of supernatural communication.</p>
      </Section>

      <Section id="not-advice">
        <h2>Not Religious, Medical, or Professional Advice</h2>
        <p>Nothing on Paramvani constitutes or should be construed as:</p>
        <ul>
          <li>Religious instruction, doctrine, or authoritative spiritual guidance</li>
          <li>Medical, mental health, or psychological advice</li>
          <li>Legal, financial, or professional advice of any kind</li>
        </ul>
        <p>If you are experiencing mental health difficulties, a personal crisis, or require genuine spiritual counselling, please consult a qualified professional, religious leader, or mental health practitioner.</p>
        <p>Emergency helpline (India): <strong>iCall: 9152987821</strong> | <strong>Vandrevala Foundation: 1860-2662-345</strong></p>
      </Section>

      <Section id="context">
        <h2>Spiritual &amp; Cultural Context</h2>
        <p>Paramvani is created with deep respect for Hindu traditions, scriptures, and spiritual values. Our AI personas are designed to reflect positive, uplifting, and dharmic principles.</p>
        <p>However, we acknowledge that:</p>
        <ul>
          <li>Different traditions, sects, and scholars may interpret scriptures differently.</li>
          <li>The AI cannot represent the full depth, nuance, or lived experience of any spiritual tradition.</li>
          <li>Users should approach conversations as a starting point for personal reflection, not as definitive spiritual truth.</li>
        </ul>
        <p>We are committed to treating all faiths with dignity. If you feel any content is disrespectful, please report it via our <a href="/community-guidelines">Community Guidelines</a> page.</p>
      </Section>

      <Section id="third-party">
        <h2>Third-Party AI Services</h2>
        <p>Paramvani uses various third-party AI and technology services for:</p>
        <ul>
          <li>Generating text responses from our AI personas.</li>
          <li>Text-to-speech audio generation of deity voices.</li>
          <li>Transcribing voice inputs (when used).</li>
        </ul>
        <p>Your inputs are sent to these services solely for the purpose of generating responses. We do not authorise these providers to use your data for training their own models. Their respective privacy policies apply to data processed by them.</p>
      </Section>

      <Section id="warranty">
        <h2>No Warranty</h2>
        <p>Paramvani makes no representations or warranties that:</p>
        <ul>
          <li>The service will be available continuously or error-free.</li>
          <li>AI responses will be accurate, complete, or appropriate for your specific situation.</li>
          <li>The platform will meet your spiritual or personal expectations.</li>
        </ul>
        <p>Use of Paramvani is at your own risk. We are not liable for any emotional, spiritual, or other harm arising from reliance on AI-generated content.</p>
      </Section>

      <Section id="user">
        <h2>User Responsibility</h2>
        <p>By using Paramvani, you acknowledge and accept that:</p>
        <ul>
          <li>You are interacting with an AI system, not a real deity, spiritual guide, or human.</li>
          <li>You will exercise independent judgment and critical thinking in evaluating AI responses.</li>
          <li>You are solely responsible for decisions made based on content from this platform.</li>
          <li>You will not form unhealthy attachments to or dependencies on the AI personas.</li>
        </ul>
      </Section>
    </>
  );
}

function ContentHI() {
  return (
    <>
      <Section id="nature">
        <h2>सेवा की प्रकृति</h2>
        <InfoBox>
          <strong>परमवाणी एक AI-संचालित मनोरंजन और आध्यात्मिक अन्वेषण मंच है।</strong> यह कोई धार्मिक प्राधिकरण, आध्यात्मिक मार्गदर्शक, परामर्शदाता या किसी भी प्रकार की पेशेवर या धार्मिक सलाह का विकल्प नहीं है।
        </InfoBox>
        <p>परमवाणी हिंदू देवताओं और आध्यात्मिक अवधारणाओं से प्रेरित नकली संवादात्मक अनुभव (simulated conversational experiences) बनाती है। ये अनुभव व्यक्तिगत प्रतिबिंब, सांस्कृतिक संबंध और मनोरंजन के लिए डिज़ाइन किए गए हैं। वे लार्ज लैंग्वेज मॉडल (LLM) AI तकनीक द्वारा संचालित हैं।</p>
      </Section>

      <Section id="ai">
        <h2>AI-जनित सामग्री प्रकटीकरण</h2>
        <p>परमवाणी के दिव्य अवतारों (भगवान विष्णु, भगवान हनुमान और अन्य सहित) द्वारा उत्पन्न सभी प्रतिक्रियाएं हैं:</p>
        <ul>
          <li><strong>कृत्रिम रूप से उत्पन्न:</strong> एक लार्ज लैंग्वेज मॉडल (LLM) द्वारा, न कि किसी मानव या आध्यात्मिक प्राधिकरण द्वारा।</li>
          <li><strong>आधिकारिक नहीं:</strong> वे किसी भी वास्तविक देवता, धार्मिक संगठन या आध्यात्मिक संस्था के विचारों, शिक्षाओं या शब्दों का प्रतिनिधित्व नहीं करते हैं।</li>
          <li><strong>संभावित रूप से गलत:</strong> AI गलतियाँ कर सकता है, मतिभ्रम (hallucinations) पैदा कर सकता है, या संदर्भ से बाहर जानकारी प्रस्तुत कर सकता है।</li>
          <li><strong>प्रासंगिक रूप से सीमित:</strong> AI सभी शास्त्रीय या धार्मिक बारीकियों को सटीक रूप से प्रतिबिंबित नहीं कर सकता है।</li>
        </ul>
        <p>AI अवतार चिंतनशील, सकारात्मक जुड़ाव के लिए बनाई गई रचनात्मक व्याख्याएं हैं। वे चैनलाइजिंग (channeling), भविष्यवाणी, या किसी भी प्रकार का अलौकिक संचार नहीं हैं।</p>
      </Section>

      <Section id="not-advice">
        <h2>धार्मिक, चिकित्सा या पेशेवर सलाह नहीं</h2>
        <p>परमवाणी पर कुछ भी इसके रूप में नहीं माना जाना चाहिए:</p>
        <ul>
          <li>धार्मिक निर्देश, सिद्धांत, या आधिकारिक आध्यात्मिक मार्गदर्शन</li>
          <li>चिकित्सा, मानसिक स्वास्थ्य, या मनोवैज्ञानिक सलाह</li>
          <li>किसी भी प्रकार की कानूनी, वित्तीय या पेशेवर सलाह</li>
        </ul>
        <p>यदि आप मानसिक स्वास्थ्य कठिनाइयों, व्यक्तिगत संकट का सामना कर रहे हैं, या वास्तविक आध्यात्मिक परामर्श की आवश्यकता है, तो कृपया किसी योग्य पेशेवर, धार्मिक नेता या मानसिक स्वास्थ्य चिकित्सक से परामर्श लें।</p>
        <p>आपातकालीन हेल्पलाइन (भारत): <strong>iCall: 9152987821</strong> | <strong>Vandrevala Foundation: 1860-2662-345</strong></p>
      </Section>

      <Section id="context">
        <h2>आध्यात्मिक और सांस्कृतिक संदर्भ</h2>
        <p>परमवाणी हिंदू परंपराओं, शास्त्रों और आध्यात्मिक मूल्यों के प्रति गहरे सम्मान के साथ बनाई गई है। हमारे AI अवतार सकारात्मक, उत्थानकारी और धार्मिक सिद्धांतों को प्रतिबिंबित करने के लिए डिज़ाइन किए गए हैं।</p>
        <p>हालांकि, हम स्वीकार करते हैं कि:</p>
        <ul>
          <li>विभिन्न परंपराएं, संप्रदाय और विद्वान शास्त्रों की अलग-अलग व्याख्या कर सकते हैं।</li>
          <li>AI किसी भी आध्यात्मिक परंपरा की पूरी गहराई, बारीकियों या जीवित अनुभव का प्रतिनिधित्व नहीं कर सकता है।</li>
          <li>उपयोगकर्ताओं को बातचीत को व्यक्तिगत प्रतिबिंब के प्रारंभिक बिंदु के रूप में देखना चाहिए, न कि निश्चित आध्यात्मिक सत्य के रूप में।</li>
        </ul>
        <p>हम सभी धर्मों के साथ सम्मानपूर्वक व्यवहार करने के लिए प्रतिबद्ध हैं। यदि आपको लगता है कि कोई भी सामग्री अपमानजनक है, तो कृपया हमारे <a href="/community-guidelines">समुदाय दिशानिर्देश</a> पृष्ठ के माध्यम से इसकी रिपोर्ट करें।</p>
      </Section>

      <Section id="third-party">
        <h2>तृतीय-पक्ष AI सेवाएं</h2>
        <p>परमवाणी विभिन्न तृतीय-पक्ष AI और प्रौद्योगिकी सेवाओं का उपयोग करती है:</p>
        <ul>
          <li>हमारे AI अवतारों से पाठ (text) प्रतिक्रियाएं उत्पन्न करने के लिए।</li>
          <li>देवता की आवाज़ के लिए पाठ-से-भाषण (text-to-speech) जनरेशन के लिए।</li>
          <li>वॉयस इनपुट (जब उपयोग किया जाता है) को ट्रांसक्राइब करने के लिए।</li>
        </ul>
        <p>आपके इनपुट इन सेवाओं को केवल प्रतिक्रियाएं उत्पन्न करने के उद्देश्य से भेजे जाते हैं। हम इन प्रदाताओं को अपने स्वयं के मॉडल के प्रशिक्षण के लिए आपके डेटा का उपयोग करने के लिए अधिकृत नहीं करते हैं। उनकी संबंधित गोपनीयता नीतियां उनके द्वारा संसाधित डेटा पर लागू होती हैं.</p>
      </Section>

      <Section id="warranty">
        <h2>कोई वारंटी नहीं</h2>
        <p>परमवाणी कोई प्रतिनिधित्व या वारंटी नहीं देती है कि:</p>
        <ul>
          <li>सेवा लगातार या त्रुटि मुक्त उपलब्ध होगी।</li>
          <li>AI प्रतिक्रियाएं आपकी विशिष्ट स्थिति के लिए सटीक, पूर्ण या उपयुक्त होंगी।</li>
          <li>मंच आपकी आध्यात्मिक या व्यक्तिगत अपेक्षाओं को पूरा करेगा।</li>
        </ul>
        <p>परमवाणी का उपयोग आपके अपने जोखिम पर है। हम AI-जनित सामग्री पर निर्भरता से उत्पन्न होने वाले किसी भी भावनात्मक, आध्यात्मिक या अन्य नुकसान के लिए उत्तरदायी नहीं हैं।</p>
      </Section>

      <Section id="user">
        <h2>उपयोगकर्ता की जिम्मेदारी</h2>
        <p>परमवाणी का उपयोग करके, आप स्वीकार करते हैं और सहमत हैं कि:</p>
        <ul>
          <li>आप एक AI सिस्टम के साथ बातचीत कर रहे हैं, न कि किसी वास्तविक देवता, आध्यात्मिक मार्गदर्शक या इंसान के साथ।</li>
          <li>आप AI प्रतिक्रियाओं के मूल्यांकन में स्वतंत्र निर्णय और आलोचनात्मक सोच का प्रयोग करेंगे।</li>
          <li>आप इस मंच से सामग्री के आधार पर लिए गए निर्णयों के लिए पूरी तरह जिम्मेदार हैं।</li>
          <li>आप AI अवतारों के प्रति अस्वस्थ जुड़ाव या निर्भरता नहीं बनाएंगे।</li>
        </ul>
      </Section>
    </>
  );
}

export default function DisclaimerPage() {
  const { lang } = useLang();
  return (
    <LegalLayout
      eyebrow={lang === 'hi' ? "कानूनी · AI प्रकटीकरण" : "Legal · AI Disclosure"}
      title={lang === 'hi' ? "अस्वीकरण और AI प्रकटीकरण" : "Disclaimer & AI Disclosure"}
      lastUpdated="August 24, 2025"
      toc={lang === 'hi' ? TOC_HI : TOC_EN}
      currentHref="/disclaimer"
    >
      {lang === 'hi' ? <ContentHI /> : <ContentEN />}
    </LegalLayout>
  );
}
